export default {
  login: "Tech-sensei",
  id: 87545908,
  node_id: "MDQ6VXNlcjg3NTQ1OTA4",
  avatar_url: "https://avatars.githubusercontent.com/u/87545908?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Tech-sensei",
  html_url: "https://github.com/Tech-sensei",
  followers_url: "https://api.github.com/users/Tech-sensei/followers",
  following_url:
    "https://api.github.com/users/Tech-sensei/following{/other_user}",
  gists_url: "https://api.github.com/users/Tech-sensei/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/Tech-sensei/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Tech-sensei/subscriptions",
  organizations_url: "https://api.github.com/users/Tech-sensei/orgs",
  repos_url: "https://api.github.com/users/Tech-sensei/repos",
  events_url: "https://api.github.com/users/Tech-sensei/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/Tech-sensei/received_events",
  type: "User",
  site_admin: false,
  name: "Tobiloba Ibraheem",
  company: null,
  blog: "",
  location: "Nigeria,Lagos",
  email: null,
  hireable: null,
  bio: "I am both driven and self-motivated, and I am constantly experimenting with new technologies and techniques. I am very passionate about Web Development.",
  twitter_username: "Im_Tobilobah",
  public_repos: 26,
  public_gists: 0,
  followers: 62,
  following: 55,
  created_at: "2021-07-16T19:23:50Z",
  updated_at: "2023-01-27T17:23:29Z",
};
